### ISSUE TITLE
Long sentence cause onnxruntime error

### ISSUE THREAD

**Issue by ly1984** [Masao-Someki/espnet_onnx#24]
First of all, thank you for you great work, I've converted the model to onnx successfully, but I found an issue ,When I synthesis a long sentence, will cause onnx runtime error.

Traceback (most recent call last):
  File "infer_onnx.py", line 39, in <module>
    wav = text2speech(text)["wav"]
  File "/opt/conda/lib/python3.8/site-packages/espnet_onnx/tts/tts_model.py", line 79, in __call__
    output_dict = self.tts_model(text, options)
  File "/opt/conda/lib/python3.8/site-packages/espnet_onnx/tts/model/tts_models/vits.py", line 59, in __call__
    wav, att_w, dur = self.model.run(output_names, input_dict)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gather node. Name:'Gather_3704' Status Message: indices element out of data bounds, idx=2595 must be within the inclusive range [-512,511]

**Comment by Masao-Someki** [comment]
Hi @ly1984, thank you for using `espnet_onnx`, and report the bug!

This is caused by the RelativePositionalEncoding. The maximum sequence length is currently set to 512, so you cannot synthesize sequences longer than 512.
The maximum length of OnnxPositionalEncoding is set in [this line](https://github.com/Masao-Someki/espnet_onnx/blob/a5e0882abe6eb471f68c6f111583e2c32e2b82e3/espnet_onnx/export/asr/models/language_models/embed.py#L52)
So, please modify 512 to another value and convert your model again.

I'm planning to refactor this project in the next PR, so I will fix this in it!

**Comment by ly1984** [comment]
Thank you for your quick response, I‘ve modified MAX_SEQ_LEN = 512 in espnet_onnx/utils/torch_function.py, everything works fine now.

**Comment by Masao-Someki** [comment]
Oh, maybe I told you the wrong answer...
Good to hear that everything works fine!

**Comment by unparalleled-ysj** [comment]
@Masao-Someki When I use vits onnx model I had the same problem, I am using the latest version espnet_onnx, It seems that it is not a problem that the sequence length exceeds 512,  same text, jets everything works fine

**after convert token to id , len(text_ints) is 231 !**
2022-06-28 14:37:45.460635020 [E:onnxruntime:, sequential_executor.cc:364 Execute] Non-zero status code returned while running Gather node. Name:'Gather_3876' Status Message: indices element out of data bounds, idx=1172 must be within the inclusive range [-512,511]
Traceback (most recent call last):
  File "inference.py", line 16, in <module>
    output_dict = tts(text)
  File "/work/espnet_onnx/tts_model/text2speech.py", line 62, in __call__
    output_dict = self.tts_model(text, **options)
  File "/work/espnet_onnx/tts_model/model/vits.py", line 49, in __call__
    wav, att_w, dur = self.model.run(output_names, input_dict)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gather node. Name:'Gather_3876' Status Message: indices element out of data bounds, idx=1172 must be within the inclusive range [-512,511]

**Comment by Masao-Someki** [comment]
@unparalleled-ysj
Am I correct that you have the following problems?
- You cannot execute inference the sequence longer than 512 in VITS. And you can infer with JETS, with the same text?
- In VITS, the sequence length after `tokenizer.text2tokens` is too short.

**Comment by unparalleled-ysj** [comment]
> @unparalleled-ysj
> 
> Am I correct that you have the following problems?
> 
> - You cannot execute inference the sequence longer than 512 in VITS. And you can infer with JETS, with the same text?
> 
> - When using the VITS, the sequence length after `tokenizer.text2tokens` is too short.

Hi @Masao-Someki  As I said above that I inference the sequence which has len(token_ints) is 231 in VITS encounter error but in JETS everything works fine. So I think it seems not a problem that the sequence length exceeds 512 result in

**Comment by Masao-Someki** [comment]
Hi @unparalleled-ysj, I encountered the same bug with a sequence length is like 100 - 200.
I found that the following line causes this problem!
When we set `max_seq_len = 1024` and `make_pad_mask` assume that the maximum sequence length is 1024. However, in this line, the value of `y_lengths` is going to be the output length of wav, which is usually larger than `max_seq_len` when the input sequence length is large. 
I will replace this part with `torch.ones`, so that everything would work file!
https://github.com/Masao-Someki/espnet_onnx/blob/0d5d2d057583b418b2a98dd50eb1845725b380f5/espnet_onnx/export/tts/models/tts_models/vits.py#L178
